services:
  - type: web
    name: motor-qr-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt --no-cache-dir
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MOTOR_ADMIN_PASSWORD
        value: "admin123"  # Change this to a secure password in the Render dashboard
